### ISSUE TITLE
Reorder table

### ISSUE THREAD

**Issue by feinfinger** [waltz-controls/waltz#213]
It would be great to be able to reorder a table column and row-wise.

**Comment by Ingvord** [comment]
@feinfinger , thanks for the issue!

As in #155 this will require some non-trivial implementation. But will see

**Comment by Ingvord** [comment]
I have found a solution!

One has to use datatable's [`externalData`](https://docs.webix.com/api__datamove_externaldata_config.html) function in conjunction with `onBeforeDrop` event handler. This way it is super easy to implement row-wise DnD reordering.

For columns `dragColumn:true`

**Comment by Ingvord** [comment]
Done in  34b6ebc The order won't be preserved upon restart though. This can be implemented later though
