### ISSUE TITLE
Improve BeamtimesDb Widget

### ISSUE THREAD

**Issue by Ingvord** [waltz-controls/waltz#234]
Track [here](https://github.com/hzg-wpi/beamtimedb-war-plugin/issues)

- [x] [#1](https://github.com/hzg-wpi/beamtimedb-war-plugin/issues/1)
- [x] [#2](https://github.com/hzg-wpi/beamtimedb-war-plugin/issues/2)
- [x] [#3](https://github.com/hzg-wpi/beamtimedb-war-plugin/issues/3)
- [x] [#4](https://github.com/hzg-wpi/beamtimedb-war-plugin/issues/4)

**Comment by HelgaMond** [comment]
Done in hzg-wpi/beamtimedb-war-plugin
