### ISSUE TITLE
Setup WALTZ 1.0.10 using docker haproxy 

### ISSUE THREAD

**Issue by bala4901** [waltz-controls/waltz#265]
Hi, May I know there is support rest api 1.1

**Comment by Ingvord** [comment]
@bala4901 waltz uses [tango-rest-client](https://github.com/waltz-controls/tango-rest-client) which supports only REST API v1.1

Hope this answers your question

**Comment by bala4901** [comment]
I am sorry. I think I do not explain clearly. 
In document which explained Waltz support till  [https://github.com/waltz-controls/waltz#developer-requirements](RC4).

However, currently [https://github.com/tango-controls/rest-server](Tango Rest Server 2.1/2.2) is supported up to Tango REST-API version 1.1.

I had try to install using Rest-server (docker). Waltz connecteed but with json error.


![image](https://user-images.githubusercontent.com/498877/119224721-031a2e00-bb2a-11eb-9ae3-b785f57d82c3.png)

I have 2 question:
1. Waltz 1.0.10 is possible to support Tango REST-API version 1.1?
2.  Where to get the detail logs for the waltz?

Best regards

**Comment by Ingvord** [comment]
The document is outdated - currently supported version of Tango REST API is v1.1

> Waltz 1.0.10 is possible to support Tango REST-API version 1.1?

1.0.10 should perfectly work together with rest-server 2.1+ 

However they both must be deployed at the same servlet container i.e. put tango.war and waltz.war together into Apache Tomcat's webapps folder. 

If you want to use dockers you need to setup a proxy e.g. HAProxy like here - [see docker-compose](https://github.com/waltz-controls/waltz/blob/epics-demo/docker-compose.yml)

These are required to eliminate CORS issues 

> Where to get the detail logs for the waltz?

I use DevTools built-in to browser (usually you need to press F12)

**Comment by bala4901** [comment]
thank @Ingvord I had implement as you commented. 

After implementing the HAProxy, i get some error. Can you give me some guides whether can clear the errors.
It said Data Loading error.

![image](https://user-images.githubusercontent.com/498877/119234960-7176e480-bb5a-11eb-93d2-fb99b287070d.png)

![image](https://user-images.githubusercontent.com/498877/119234938-599f6080-bb5a-11eb-8e1b-828c9ef3b892.png)

**Comment by Ingvord** [comment]
Hm... you also need [user-context](https://github.com/waltz-controls/user-context)

I will update the docs. Thanks for reporting!

**Comment by bala4901** [comment]
Hi @Ingvord 

Thank you for your support. After adding the [user-context.war](https://github.com/waltz-controls/user-context). It can be run.
I attached for my configuration for docker to run the waltz.

[waltz1_0_11-docker.zip](https://github.com/waltz-controls/waltz/files/6526912/waltz1_0_11-docker.zip)

Due to file size the WAR I do not including in the zip file:
- [waltz.war](https://github.com/waltz-controls/waltz/releases/tag/1.0.10)
- [user-context.war](https://github.com/waltz-controls/user-context)
- [tango.war](https://github.com/tango-controls/rest-server/releases/tag/rest-server-2.1)
