### ISSUE TITLE
Waltz malformat for Tango rest-api 1.1

### ISSUE THREAD

**Issue by bala4901** [waltz-controls/waltz#266]
For those devices that not running and has errors. Waltz unable to read and will give errors.
Check in the console, it will give status 400 which is malformat.
And check on the console > Network, there is reply by Tango REST-API. but do not treat well by Waltz.
I attached the print screens for your reference

![image](https://user-images.githubusercontent.com/498877/119237031-f0711a80-bb64-11eb-9240-30a4005c1bc5.png)

![image](https://user-images.githubusercontent.com/498877/119236930-514c2300-bb64-11eb-85a6-c15c664c3eca.png)

![image](https://user-images.githubusercontent.com/498877/119236955-7771c300-bb64-11eb-9d43-42f88664f540.png)

**Comment by Ingvord** [comment]
@bala4901 

Thanks for the images!

This is expected behavior: for not running devices Waltz shows error notification popup (first image, top right corner). The detials are in the log (small info icon, bottom right corner)

**Comment by Ingvord** [comment]
I will close this issue for now. If you have any more details/questions etc Please feel free to reopen it! Thanks
